module.exports = {
    CHANNEL_FILTER_TIME : 86400000, //24 hours
    EXCEPTION : -1,
    NEW_CHANNEL_ADDED : 1,
    EXISTING_CHANNEL_UPDATED : 2,

    CHANNEL_COUNT_NO_USER : 4,

    JWT_EXPIRES_AFTER : "180d"
};
